mutation {
  createProviderAppointments( 
    userName: "@DJekyll",
    startTime: "2023-11-16T08:00:00.000Z"
    endTime: "2023-11-16T17:00:00.000Z"
  ) {
    id
    providerId
    startTime
    endTime
    provider {
      id
      name
      userName
    }
    status
    clientUserName
    
  }
}
