mutation {
  expireAppointments {
    id
    providerId
    startTime
    endTime
    provider {
      id
      name
      userName
    }
    status
    clientUserName
    appointmentReservationExpiration
  }
}
